import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Header from './components/Header'
import styles from '../styles/Home.module.css'
import Destaques from './components/Destaques'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Destaques />
      <div className="px-8 bg-bege h-screen flex flex-row">
        <section className="w-2/3 h-full">

        </section>
        <aside className="w-1/3 h-full">

        </aside>
      </div>
    </div>
  )
}

export default Home
